logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/logs/webapp/application.json.log
      record_log_file_path: true
  processors:
    json_parser:
      type: parse_json
      time_key: jsonPayload.time
      time_format: "%Y-%m-%dT%H:%M:%S.%fZ"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [json_parser, move_severity]
