logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/logs/webapp/*.log

  processors:
    my-app-json-parser:
      type: parse_json
      field: jsonPayload
      time_key: "@timestamp"
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
      message_key: "message"
      severity_key: "level"

  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-json-parser]


