logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/logs/webapp/application.json.log
      record_log_file_path: true
  processors:
    parse_java_multiline:
      type: parse_multiline
      match_any:
        - type: language_exceptions
          language: java
    extract_structure:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [parse_java_multiline, extract_structure, move_severity]
