name: Packer Checks

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6

      - name: Initialize Packer
        working-directory: packer-dir
        run: packer init .

      - name: Check Packer file formatting
        working-directory: packer-dir
        id: packer_fmt
        run: |
          output=$(packer fmt -recursive .)
          if [ -n "$output" ]; then
            echo "::set-output name=formatted::true"
            echo "$output"
          else
            echo "::set-output name=formatted::false"
          fi
      
      - name: Fail if formatting was needed
        if: steps.packer_fmt.outputs.formatted == 'true'
        run: |
          echo "Formatting was required for some Packer files, indicating they were not properly formatted."
          exit 1

      - name: Validate Packer Template with Variables
        working-directory: packer-dir
        run: |
          packer validate \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "artifact_path=${{ github.workspace }}/src/main/java/com/csye6225/assignment1/Assignment1Application.java" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "mysql_user=${{ secrets.MYSQL_USER }}" \
            -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" .
