name: Packer Checks

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6

      - name: Initialize Packer
        working-directory: packer-dir
        run: packer init .

      - name: Run packer fmt
        working-directory: packer-dir
        run: |
          packer fmt -check -recursive .
          if [ $? -ne 0 ]; then
            echo "Packer template formatting check failed!"
            exit 1
          fi

      - name: Validate Packer Template with Variables
        run: |
          packer validate \
            -var "artifact_path=${{ github.workspace }}/target/assignment1-1.0.0.jar" \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "mysql_user=${{ secrets.MYSQL_USER }}" \
            -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" \
            .
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}