name: Packer Checks

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6

      - name: Initialize Packer
        working-directory: packer-dir
        run: packer init .

      - name: Run packer fmt and check for unformatted files
        working-directory: packer-dir
        run: |
          # Format Packer files
          packer fmt -recursive .
          # Check if any files were modified by the formatting
          git diff --exit-code . || {
            echo "::error::Packer template formatting has modified files, indicating they were not properly formatted."
            exit 1
          }


      - name: Validate Packer Template with Variables
        working-directory: packer-dir
        run: |
          packer validate \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "artifact_path=${{ github.workspace }}/src/main/java/com/csye6225/assignment1/Assignment1Application.java" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "mysql_user=${{ secrets.MYSQL_USER }}" \
            -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" .
