name: Packer Checks

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6

      - name: Initialize Packer
        working-directory: packer-dir
        run: packer init .

      - name: Check Packer file formatting
        working-directory: packer-dir
        run: |
          # Run packer fmt and capture any output indicating files that were formatted
          output=$(packer fmt -recursive .)
          echo "$output"
          
          # If output is not empty, fail the step
          if [ -n "$output" ]; then
            echo "Formatting was required for some Packer files, indicating they were not properly formatted. Please format them as shown above."
            exit 1
          else
            echo "All Packer files are properly formatted."
          fi


      - name: Validate Packer Template with Variables
        working-directory: packer-dir
        run: |
          packer validate \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "artifact_path=${{ github.workspace }}/src/main/java/com/csye6225/assignment1/Assignment1Application.java" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "mysql_user=${{ secrets.MYSQL_USER }}" \
            -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" .
