name: Packer Checks

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6

      - name: Initialize Packer
        working-directory: packer-dir
        run: packer init .

      - name: Run packer fmt
        working-directory: packer-dir
        run: |
          packer fmt -check -recursive . || true # Prevent immediate exit
          fmt_exit_code=$?
          echo "packer fmt -check exit code: $fmt_exit_code"
          if [ $fmt_exit_code -ne 0 ]; then
            echo "Packer template formatting check failed!"
            exit 1
          fi


      - name: Validate Packer Template with Variables
        working-directory: packer-dir
        run: |
          packer validate \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "artifact_path=${{ github.workspace }}/src/main/java/com/csye6225/assignment1/Assignment1Application.java" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "mysql_user=${{ secrets.MYSQL_USER }}" \
            -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" .
